name: Biamp
description: audio

red: "#D9272E"
darkerGreySelect: "#494647"
darkGrey: "#4f4e4e"
medGrey: "#585556"
lightGrey: "#C8C7C7"
grey60: "#808284"
paleGrey: "#F4F4F4"
lightBlue: "#E3EAEA"

desktop: 1420
tablet: 700

defaults:
 -
  scope:
   path: "" # an empty string here means all files in the project
   type: "pages"
  values:
   layout: "default"